name: Test suite

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lintcode:
    name: Biome lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - name: "install dependencies"
        run: npm ci

      - name: "run biome"
        run: npm run lint

  tests:
    name: Meteor tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '3.4'

      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - name: "install dependencies"
        run: npm ci

      - name: "run tests"
        run: npm run test:ci
